"""Profile schema (V3-profiles): the on-disk/in-memory shape of a
claudeglass profile (plan Appendix A7 and the "Milestone v0.3 --
baseline capture, archetype, profiles, apply" section) and the allowlist
that is the *single source of truth* for what a profile may contain.

A profile only ever names a documented Claude Code lever -- never a
value the harness has no way to honour -- so the schema itself is the
enforcement point the plan asks for ("the schema rejects anything else
so a profile can never promise an effect the harness cannot deliver",
quoted again in ``docs/api.md``'s ``POST /api/profiles`` note). Every
allowlisted key carries its permitted type/values, which *kind* of lever
it is (a top-level settings key, a per-agent frontmatter path, or an
environment variable name), and a documentation reference, so a
validation failure and a rendered doc table both come from the exact
same data (see ``docs/profiles.md``, generated by hand from these three
dicts to keep them from drifting apart).

This module is deliberately the only place in this package that
constructs or serialises a :class:`Profile` -- ``catalogue.py`` and
``diff.py`` both import it rather than duplicating any of this.

Deviations from the plan/brief, reported rather than made silently (see
``model.py``'s module docstring for this project's convention on this):

- **``notes`` is placed before the ``[settings]``/``[agents.*]``/``[env]``
  tables in :func:`dump_profile`'s output, not after ``[env]`` the way
  Appendix A7's illustrative snippet writes it.** Appendix A7 places
  ``notes = "..."`` as the very last line, directly below an
  ``[env]`` table with no further table header — but TOML has no
  "closed" table: every bare ``key = value`` line belongs to the most
  recently opened table header, so a real TOML parser (``tomllib``, and
  every other implementation) would fold that ``notes`` value into
  ``[env]`` itself rather than reading it as a top-level field. Since
  ``Profile.notes`` is a genuine top-level field (per this work
  package's own dataclass spec), :func:`dump_profile` writes it as a
  bare top-level key ahead of any table header, which is both valid
  TOML and round-trips correctly. A7's ordering is kept for the
  ``id``/``name``/``for``/``archetype``/``[settings]``/``[agents.*]``/
  ``[env]`` sections exactly as shown.
- **``recommend.py``'s baseline-bloat rule carries no lever.** It used
  to emit a bare ``"mcpServers"``, which is no settings key (MCP servers
  live in ``~/.claude.json`` and ``.mcp.json``), so ``--patch-set``
  printed a settings change that doesn't exist, and
  :data:`RECOMMEND_LEVER_MAP` mapped it to ``disabledMcpjsonServers``.
  Its fix is a prompt now, and the mapping is gone. Every lever
  ``recommend.py``/``ttl.py`` still emits resolves to an allowlisted key;
  see ``tests/test_profiles_schema.py`` for the regression test.
"""

from __future__ import annotations

import re
import tomllib
from dataclasses import dataclass, field, fields
from pathlib import Path

__all__ = [
    "LeverSpec",
    "Profile",
    "ProfileError",
    "SETTINGS_ALLOWLIST",
    "AGENT_ALLOWLIST",
    "ENV_ALLOWLIST",
    "ARCHETYPES",
    "RECOMMEND_LEVER_MAP",
    "validate",
    "load_profile",
    "loads_profile",
    "load_dict",
    "dump_profile",
    "recommend_lever_key",
]


class ProfileError(ValueError):
    """A profile document failed :func:`validate`. ``problems`` carries
    the full list of messages ``validate`` produced (never just the
    first one), so a caller printing this exception's ``str()`` sees
    every problem at once, matching :func:`validate`'s own contract."""

    def __init__(self, problems: list[str]) -> None:
        self.problems = list(problems)
        super().__init__("; ".join(self.problems) if self.problems else "invalid profile")


@dataclass(frozen=True, slots=True)
class LeverSpec:
    """One allowlisted key's shape: its permitted Python type, which kind
    of lever it is (see the three ``scope_kind`` values below), the
    values an ``"enum"`` kind accepts, the inclusive range an ``"int"``
    kind accepts, and a documentation anchor for :func:`validate`'s
    error text / ``docs/profiles.md``'s table.

    ``scope_kind`` is one of:

    - ``"settings"`` -- a top-level Claude Code ``settings.json`` key.
    - ``"agent frontmatter"`` -- a ``.claude/agents/<name>.md`` frontmatter
      field (only meaningful nested under ``Profile.agents["<name>"]``).
    - ``"env"`` -- an environment variable *name* (the allowlist governs
      which names a profile may mention; the value is always a free-form
      string the user supplies at apply time, per the plan's "names
      only here; values supplied at apply time" A7 comment).
    """

    kind: str  # "str" | "enum" | "int" | "bool" | "list[str]" | "map[str,bool]" | "map[str,enum]"
    scope_kind: str  # "settings" | "agent frontmatter" | "env"
    values: tuple[str, ...] | None = None
    min: int | None = None
    max: int | None = None
    doc_ref: str = ""


# -- the allowlist: single source of truth for what a profile may contain --

_EFFORT_LEVELS = ("low", "medium", "high", "xhigh", "max")
_TTL_VALUES = ("5m", "1h")
#: ``skillOverrides`` values: listed with its description, by name only,
#: only for you to invoke with /name, or not at all.
_SKILL_VISIBILITY = ("on", "name-only", "user-invocable-only", "off")

#: Top-level ``settings.json`` overlay keys a profile may set.
SETTINGS_ALLOWLIST: dict[str, LeverSpec] = {
    "model": LeverSpec(
        "str", "settings",
        doc_ref="docs/config-layers.md#the-layer-model",
    ),
    "effortLevel": LeverSpec(
        "enum", "settings", values=_EFFORT_LEVELS,
        doc_ref="docs/config-layers.md#what-each-layer-records-settings_layerslayer",
    ),
    "autoCompactWindow": LeverSpec(
        "int", "settings", min=0, max=1_000_000,
        doc_ref="docs/config-layers.md#what-each-layer-records-settings_layerslayer",
    ),
    "outputStyle": LeverSpec(
        "str", "settings",
        doc_ref="docs/config-layers.md#what-each-layer-records-settings_layerslayer",
    ),
    "promptCacheTtl": LeverSpec(
        "enum", "settings", values=_TTL_VALUES,
        doc_ref="docs/api.md#get-apittl",
    ),
    "subagentPromptCacheTtl": LeverSpec(
        "enum", "settings", values=_TTL_VALUES,
        doc_ref="docs/api.md#get-apittl",
    ),
    # Objects keyed by name: apply merges them into the existing object,
    # so a profile turning one plugin off leaves every other plugin alone.
    "enabledPlugins": LeverSpec(
        "map[str,bool]", "settings",
        doc_ref="docs/config-layers.md#content_layers",
    ),
    "skillOverrides": LeverSpec(
        "map[str,enum]", "settings", values=_SKILL_VISIBILITY,
        doc_ref="docs/profiles.md#settings-top-level-settingsjson-overlay-keys",
    ),
    "disabledMcpjsonServers": LeverSpec(
        "list[str]", "settings",
        doc_ref="docs/config-layers.md#claude_json--the-claudejson-cross-check",
    ),
    "enabledMcpjsonServers": LeverSpec(
        "list[str]", "settings",
        doc_ref="docs/config-layers.md#claude_json--the-claudejson-cross-check",
    ),
    "alwaysThinkingEnabled": LeverSpec(
        "bool", "settings",
        doc_ref="docs/config-layers.md#redaction-rule-settings-and-agent-frontmatter-alike",
    ),
    "autoCompactEnabled": LeverSpec(
        "bool", "settings",
        doc_ref="docs/config-layers.md#redaction-rule-settings-and-agent-frontmatter-alike",
    ),
    "cleanupPeriodDays": LeverSpec(
        "int", "settings", min=0, max=3650,
        doc_ref="docs/config-layers.md#redaction-rule-settings-and-agent-frontmatter-alike",
    ),
    # COV-09: the deprecated Boolean recommend.py's env-attribution-deprecated
    # rule flags in favour of the `attribution` setting.
    "includeCoAuthoredBy": LeverSpec(
        "bool", "settings",
        doc_ref="docs/config-layers.md#redaction-rule-settings-and-agent-frontmatter-alike",
    ),
    # PROF-08/D5: fast mode is a documented per-model price premium (a
    # flat multiplier over standard rates -- pricing.toml's [.fast]
    # tables), traded for a faster reply. whatif.py's "fastMode": False
    # branch reprices the window's fast-billed replies at standard to
    # show what turning it off would save (see whatif._fast_mode).
    "fastMode": LeverSpec(
        "bool", "settings",
        doc_ref="docs/config-layers.md#redaction-rule-settings-and-agent-frontmatter-alike",
    ),
}

#: ``agents.<name>`` frontmatter patch keys a profile may set. The dotted
#: ``"experimental.cacheTtl"`` key is stored dotted (never nested) once
#: normalised -- see :func:`_normalise_agent_dict`.
AGENT_ALLOWLIST: dict[str, LeverSpec] = {
    "model": LeverSpec("str", "agent frontmatter", doc_ref="docs/config-layers.md#effective_agents"),
    "effort": LeverSpec(
        "enum", "agent frontmatter", values=_EFFORT_LEVELS,
        doc_ref="docs/config-layers.md#effective_agents",
    ),
    "maxTurns": LeverSpec(
        "int", "agent frontmatter", min=1, max=1_000_000,
        doc_ref="docs/config-layers.md#effective_agents",
    ),
    "omitClaudeMd": LeverSpec("bool", "agent frontmatter", doc_ref="docs/sections-reference.md"),
    "memory": LeverSpec("str", "agent frontmatter", doc_ref="docs/config-layers.md#content_layers"),
    "tools": LeverSpec("list[str]", "agent frontmatter", doc_ref="docs/config-layers.md#content_layers"),
    "disallowedTools": LeverSpec("list[str]", "agent frontmatter", doc_ref="docs/config-layers.md#content_layers"),
    "skills": LeverSpec("list[str]", "agent frontmatter", doc_ref="docs/config-layers.md#content_layers"),
    "mcpServers": LeverSpec("list[str]", "agent frontmatter", doc_ref="docs/config-layers.md#content_layers"),
    "experimental.cacheTtl": LeverSpec(
        "enum", "agent frontmatter", values=_TTL_VALUES,
        doc_ref="docs/config-layers.md#effective_agents",
    ),
}

#: Environment variable *names* a profile may mention (the value is
#: always a free-form string supplied at apply time -- see
#: ``LeverSpec``'s docstring).
ENV_ALLOWLIST: dict[str, LeverSpec] = {
    name: LeverSpec("str", "env", doc_ref="docs/config-layers.md#environment-variables")
    for name in (
        "CLAUDE_CODE_PROMPT_CACHE_TTL",
        "CLAUDE_CODE_SUBAGENT_PROMPT_CACHE_TTL",
        "CLAUDE_CODE_SUBAGENT_MODEL",
        "MAX_THINKING_TOKENS",
        "CLAUDE_AUTOCOMPACT_PCT_OVERRIDE",
        "MAX_MCP_OUTPUT_TOKENS",
        "BASH_MAX_OUTPUT_LENGTH",
        "DISABLE_NON_ESSENTIAL_MODEL_CALLS",
        "ANTHROPIC_DEFAULT_OPUS_MODEL",
        "ANTHROPIC_DEFAULT_SONNET_MODEL",
        "ANTHROPIC_DEFAULT_HAIKU_MODEL",
        "ANTHROPIC_DEFAULT_FABLE_MODEL",
        # COV-09: recommend.py's five new env-lever rules.
        "DISABLE_PROMPT_CACHING",
        "DISABLE_PROMPT_CACHING_SONNET",
        "DISABLE_PROMPT_CACHING_OPUS",
        "DISABLE_PROMPT_CACHING_HAIKU",
        "DISABLE_PROMPT_CACHING_FABLE",
        "ENABLE_TOOL_SEARCH",
        "CLAUDE_CODE_MAX_OUTPUT_TOKENS",
        # Overrides autoCompactWindow while set (docs/en/env-vars.md).
        "CLAUDE_CODE_AUTO_COMPACT_WINDOW",
    )
}

#: Every workstyle archetype ``workstyle.detect_archetype``/
#: ``corpus_archetype`` can return (``workstyle._ARCHETYPE_DESCRIPTIONS``'s
#: keys, duplicated here rather than imported so this module stays
#: import-independent of the analytics stack -- see the module docstring's
#: note that this package has no dependency beyond the standard library
#: and its own submodules).
ARCHETYPES: tuple[str, ...] = (
    "overseer-fanout",
    "plan-high-implement-low",
    "workflow-heavy",
    "effort-varied",
    "single-model",
    "chat-only",
    "mixed",
)

_ID_RE = re.compile(r"^[a-z0-9-]{1,40}$")
_BARE_TOML_KEY_RE = re.compile(r"^[A-Za-z0-9_-]+$")

_TOP_LEVEL_KEYS = {"id", "name", "for", "archetype", "settings", "agents", "env", "notes"}


# -- Profile dataclass -------------------------------------------------


@dataclass(frozen=True, slots=True)
class Profile:
    """One profile document -- either a shipped catalogue entry
    (``profiles/catalogue/<id>.toml``) or a user/API-submitted one. See
    plan Appendix A7 for the on-disk shape this mirrors field-for-field
    (``for`` renamed ``for_`` here since it is a Python keyword)."""

    id: str = ""
    name: str = ""
    for_: tuple[str, ...] = ()
    archetype: str | None = None
    settings: dict = field(default_factory=dict)
    #: agent name -> {allowlisted key: value}, keys already normalised to
    #: the dotted ``"experimental.cacheTtl"`` form.
    agents: dict = field(default_factory=dict)
    env: dict = field(default_factory=dict)
    notes: str = ""
    #: Where this profile was loaded from, if it was loaded from a file
    #: (``load_profile``) rather than a dict/string. Never written by
    #: ``dump_profile`` and never part of equality (a round trip through
    #: dump/load must compare equal regardless of where either copy came
    #: from) -- see the module docstring's "never exported" note.
    source_path: str | None = field(default=None, compare=False, repr=False)


# -- validation ----------------------------------------------------------


def _type_ok(value, spec: LeverSpec) -> bool:
    if spec.kind == "str":
        return isinstance(value, str)
    if spec.kind == "enum":
        return isinstance(value, str) and spec.values is not None and value in spec.values
    if spec.kind == "int":
        if not isinstance(value, int) or isinstance(value, bool):
            return False
        if spec.min is not None and value < spec.min:
            return False
        if spec.max is not None and value > spec.max:
            return False
        return True
    if spec.kind == "bool":
        return isinstance(value, bool)
    if spec.kind == "list[str]":
        return isinstance(value, list) and all(isinstance(item, str) for item in value)
    if spec.kind == "map[str,bool]":
        return isinstance(value, dict) and all(
            isinstance(k, str) and isinstance(v, bool) for k, v in value.items()
        )
    if spec.kind == "map[str,enum]":
        return isinstance(value, dict) and all(
            isinstance(k, str) and isinstance(v, str) and v in (spec.values or ()) for k, v in value.items()
        )
    return False  # pragma: no cover - every LeverSpec.kind above is exhaustive


def _describe_expected(spec: LeverSpec) -> str:
    if spec.kind == "enum":
        return f"one of {', '.join(spec.values or ())}"
    if spec.kind == "int":
        bounds = ""
        if spec.min is not None or spec.max is not None:
            bounds = f" between {spec.min if spec.min is not None else '-inf'} and {spec.max if spec.max is not None else 'inf'}"
        return f"an int{bounds}"
    if spec.kind == "bool":
        return "a bool"
    if spec.kind == "list[str]":
        return "a list of strings"
    if spec.kind == "map[str,bool]":
        return "a table of names to true or false"
    if spec.kind == "map[str,enum]":
        return f"a table of names to one of {', '.join(spec.values or ())}"
    return "a string"


def _normalise_agent_dict(agent_name: str, raw: dict, problems: list[str]) -> dict:
    """Returns ``raw`` with a nested ``experimental = {cacheTtl = ...}``
    table folded into the dotted ``"experimental.cacheTtl"`` key (plan:
    "accept both the dotted key and a nested ``experimental = { cacheTtl
    = ... }`` table, normalise to dotted"). Appends a problem and leaves
    the dotted key unset if both forms are given with different values,
    or if the nested table holds anything other than ``cacheTtl``."""
    out = dict(raw)
    nested = out.pop("experimental", None)
    if nested is None:
        return out
    if not isinstance(nested, dict):
        problems.append(f"agents.{agent_name}.experimental: must be a table, got {type(nested).__name__}")
        return out
    extra_keys = set(nested) - {"cacheTtl"}
    if extra_keys:
        problems.append(
            f"agents.{agent_name}.experimental: unknown key(s) {sorted(extra_keys)} "
            "(only 'cacheTtl' is allowlisted under a nested experimental table)"
        )
    if "cacheTtl" not in nested:
        return out
    dotted_value = out.get("experimental.cacheTtl")
    nested_value = nested["cacheTtl"]
    if "experimental.cacheTtl" in out and dotted_value != nested_value:
        problems.append(
            f"agents.{agent_name}: both 'experimental.cacheTtl' ({dotted_value!r}) and a nested "
            f"experimental.cacheTtl ({nested_value!r}) were given with different values"
        )
    else:
        out["experimental.cacheTtl"] = nested_value
    return out


def validate(d: dict) -> list[str]:
    """Every problem with profile document ``d`` (already-parsed TOML or
    JSON, i.e. a plain ``dict``): unknown top-level/settings/agent/env
    keys, wrong types, out-of-range values, an unknown ``archetype``, and
    an ``id`` that does not match ``^[a-z0-9-]{1,40}$``. An empty list
    means ``d`` is a valid profile. Never raises on a malformed shape --
    every check degrades to a problem message instead (matching this
    project's "never crash on a foreign shape" convention -- see
    ``config.py``/``snapshots.py``'s module docstrings)."""
    problems: list[str] = []

    if not isinstance(d, dict):
        return [f"profile: must be a table/object, got {type(d).__name__}"]

    unknown_top = sorted(set(d) - _TOP_LEVEL_KEYS)
    for key in unknown_top:
        problems.append(f"{key}: unknown top-level key")

    profile_id = d.get("id")
    if not isinstance(profile_id, str) or not profile_id:
        problems.append("id: required, must be a non-empty string")
    elif not _ID_RE.match(profile_id):
        problems.append(f"id: must match ^[a-z0-9-]{{1,40}}$, got {profile_id!r}")

    if "name" in d and not isinstance(d["name"], str):
        problems.append(f"name: must be a string, got {type(d['name']).__name__}")

    if "for" in d:
        for_value = d["for"]
        if not isinstance(for_value, list) or not all(isinstance(item, str) for item in for_value):
            problems.append("for: must be a list of strings")

    if "archetype" in d and d["archetype"] is not None:
        archetype = d["archetype"]
        if not isinstance(archetype, str) or archetype not in ARCHETYPES:
            problems.append(f"archetype: unknown archetype {archetype!r} (expected one of {', '.join(ARCHETYPES)})")

    if "notes" in d and not isinstance(d["notes"], str):
        problems.append(f"notes: must be a string, got {type(d['notes']).__name__}")

    settings = d.get("settings", {})
    if not isinstance(settings, dict):
        problems.append(f"settings: must be a table/object, got {type(settings).__name__}")
    else:
        for key, value in settings.items():
            spec = SETTINGS_ALLOWLIST.get(key)
            if spec is None:
                problems.append(f"settings.{key}: unknown key")
                continue
            if not _type_ok(value, spec):
                problems.append(f"settings.{key}: must be {_describe_expected(spec)}, got {value!r}")

    agents = d.get("agents", {})
    if not isinstance(agents, dict):
        problems.append(f"agents: must be a table/object, got {type(agents).__name__}")
    else:
        for agent_name, agent_dict in agents.items():
            if not isinstance(agent_dict, dict):
                problems.append(f"agents.{agent_name}: must be a table/object, got {type(agent_dict).__name__}")
                continue
            normalised = _normalise_agent_dict(agent_name, agent_dict, problems)
            for key, value in normalised.items():
                spec = AGENT_ALLOWLIST.get(key)
                if spec is None:
                    problems.append(f"agents.{agent_name}.{key}: unknown key")
                    continue
                if not _type_ok(value, spec):
                    problems.append(f"agents.{agent_name}.{key}: must be {_describe_expected(spec)}, got {value!r}")

    env = d.get("env", {})
    if not isinstance(env, dict):
        problems.append(f"env: must be a table/object, got {type(env).__name__}")
    else:
        for name, value in env.items():
            if name not in ENV_ALLOWLIST:
                problems.append(f"env.{name}: not an allowed environment variable name")
            elif not isinstance(value, str):
                problems.append(f"env.{name}: value must be a string, got {type(value).__name__}")

    return problems


# -- loading ---------------------------------------------------------------


def load_dict(d: dict, *, source_path: str | None = None) -> Profile:
    """Validates ``d`` (raises :class:`ProfileError` on any problem) and
    builds the :class:`Profile` it describes. This is the one function
    every loader (:func:`load_profile`, :func:`loads_profile`) and the
    service's ``POST /api/profiles`` route (which hands this function a
    JSON body already parsed into a plain dict -- see ``docs/api.md``)
    funnel through."""
    problems = validate(d)
    if problems:
        raise ProfileError(problems)

    agents_raw = d.get("agents", {}) or {}
    agents: dict = {}
    for agent_name, agent_dict in agents_raw.items():
        normalised_problems: list[str] = []
        agents[agent_name] = _normalise_agent_dict(agent_name, agent_dict, normalised_problems)
        # validate() above already proved this normalisation raises no
        # new problems for a document that passed validation -- assert
        # rather than silently trust, so a future validate()/load_dict()
        # drift is caught immediately instead of shipping a bad Profile.
        assert not normalised_problems, normalised_problems

    return Profile(
        id=d["id"],
        name=d.get("name", ""),
        for_=tuple(d.get("for", ()) or ()),
        archetype=d.get("archetype"),
        settings=dict(d.get("settings", {}) or {}),
        agents=agents,
        env=dict(d.get("env", {}) or {}),
        notes=d.get("notes", ""),
        source_path=source_path,
    )


def loads_profile(text: str) -> Profile:
    """Parses ``text`` as a TOML profile document and returns the
    :class:`Profile` it describes (see :func:`load_dict`)."""
    data = tomllib.loads(text)
    return load_dict(data)


def load_profile(path: str | Path) -> Profile:
    """Reads and parses the TOML profile document at ``path``. The
    returned :class:`Profile`'s ``source_path`` is ``str(path)``."""
    path = Path(path)
    data = tomllib.loads(path.read_text(encoding="utf-8"))
    return load_dict(data, source_path=str(path))


# -- dumping (minimal deterministic TOML emitter) ---------------------------
#
# ``tomllib`` (stdlib) is read-only -- there is no stdlib TOML writer, so
# this hand-rolls the narrow subset of TOML the schema above actually
# needs: bare top-level scalars/lists, and simple non-nested tables
# (``[settings]``, ``[agents.<name>]``, ``[env]``) of scalars/lists. Every
# section's keys are emitted in the allowlist's own fixed iteration order
# (not the ``dict``'s insertion order) so two calls with the same profile
# content always produce byte-identical output regardless of how the
# caller built the dict -- the "byte-stable ordering" this package's
# other deliverable (``diff.py``'s ``render_unified_diff``) also commits
# to, for the same reason: a diff/dump that reorders itself between runs
# is useless for a git-style comparison.


def _toml_escape(s: str) -> str:
    out = []
    for ch in s:
        if ch == "\\":
            out.append("\\\\")
        elif ch == '"':
            out.append('\\"')
        elif ch == "\n":
            out.append("\\n")
        elif ch == "\t":
            out.append("\\t")
        elif ch == "\r":
            out.append("\\r")
        elif ord(ch) < 0x20:
            out.append(f"\\u{ord(ch):04x}")
        else:
            out.append(ch)
    return "".join(out)


def _toml_string(s: str) -> str:
    return f'"{_toml_escape(s)}"'


def _toml_key(k: str) -> str:
    return k if _BARE_TOML_KEY_RE.match(k) else _toml_string(k)


def _toml_value(v) -> str:
    if isinstance(v, bool):
        return "true" if v else "false"
    if isinstance(v, int):
        return str(v)
    if isinstance(v, str):
        return _toml_string(v)
    if isinstance(v, (list, tuple)):
        return "[" + ", ".join(_toml_value(item) for item in v) + "]"
    if isinstance(v, dict):
        return "{ " + ", ".join(f"{_toml_string(k)} = {_toml_value(item)}" for k, item in v.items()) + " }"
    raise TypeError(f"cannot emit {v!r} as TOML")  # pragma: no cover - schema-validated inputs only


def dump_profile(profile: Profile) -> str:
    """Deterministic TOML text for ``profile`` -- ``source_path`` is
    never emitted (see the module/``Profile`` docstrings' "never
    exported" note). ``load_profile(io) -> dump_profile -> loads_profile``
    round-trips to an equal :class:`Profile` (excluding ``source_path``,
    which is excluded from equality too) for every value the allowlist
    permits."""
    lines: list[str] = []
    lines.append(f"id = {_toml_string(profile.id)}")
    if profile.name:
        lines.append(f"name = {_toml_string(profile.name)}")
    if profile.for_:
        lines.append(f"for = {_toml_value(list(profile.for_))}")
    if profile.archetype:
        lines.append(f"archetype = {_toml_string(profile.archetype)}")
    if profile.notes:
        lines.append(f"notes = {_toml_string(profile.notes)}")

    if profile.settings:
        lines.append("")
        lines.append("[settings]")
        for key in SETTINGS_ALLOWLIST:
            if key in profile.settings:
                lines.append(f"{_toml_key(key)} = {_toml_value(profile.settings[key])}")

    for agent_name in sorted(profile.agents):
        agent_dict = profile.agents[agent_name]
        if not agent_dict:
            continue
        lines.append("")
        lines.append(f"[agents.{_toml_key(agent_name)}]")
        for key in AGENT_ALLOWLIST:
            if key in agent_dict:
                lines.append(f"{_toml_key(key)} = {_toml_value(agent_dict[key])}")

    if profile.env:
        lines.append("")
        lines.append("[env]")
        for name in ENV_ALLOWLIST:
            if name in profile.env:
                lines.append(f"{_toml_key(name)} = {_toml_value(profile.env[name])}")

    return "\n".join(lines).rstrip("\n") + "\n"


# -- recommend.py lever coverage --------------------------------------------

#: A per-agent-type TTL lever's text, e.g. ``"experimental.cacheTtl in
#: claude-implementer.md (or subagentPromptCacheTtl for all subagents)"``
#: (``ttl.TtlTypeStats.lever``) -- duplicated from
#: ``recommend._AGENT_LEVER_RE`` rather than imported, since this module
#: must not depend on ``recommend.py`` (the dependency runs the other way:
#: a later work package's ``apply``/service routes import *this* module
#: to act on a ``Recommendation.lever`` string).
_AGENT_LEVER_RE = re.compile(r"experimental\.cacheTtl in ([^.]+)\.md")

#: Maps a bare lever string ``recommend.py`` can emit directly (a literal
#: ``lever="..."``/``lever = "..."`` in a ``Recommendation(...)`` call)
#: onto the ``(scope_kind, allowlisted key)`` pair it represents.
RECOMMEND_LEVER_MAP: dict[str, tuple[str, str]] = {
    "promptCacheTtl": ("settings", "promptCacheTtl"),
    "autoCompactWindow": ("settings", "autoCompactWindow"),
    "effortLevel": ("settings", "effortLevel"),
    "omitClaudeMd": ("agent frontmatter", "omitClaudeMd"),
    # COV-09: the deprecated-setting rule's bare settings-key lever.
    "includeCoAuthoredBy": ("settings", "includeCoAuthoredBy"),
}

#: COV-09: recommend.py's five env-var lever rules emit ``f"env:{NAME}"``
#: (one rule's own name is chosen dynamically -- whichever
#: ``DISABLE_PROMPT_CACHING*`` variant a snapshot actually has set, or the
#: bare ``DISABLE_PROMPT_CACHING`` name when more than one is), so this is
#: a *prefix* convention rather than a fixed set of literals
#: :data:`RECOMMEND_LEVER_MAP` could enumerate -- unlike the agent-lever
#: sentence form above, the part after the prefix is already the exact
#: :data:`ENV_ALLOWLIST` key, no further parsing needed.
_ENV_LEVER_PREFIX = "env:"


def recommend_lever_key(lever: str) -> tuple[str, str] | None:
    """The ``(scope_kind, allowlisted key)`` pair the raw ``lever`` string
    a ``Recommendation`` carries represents, or ``None`` if ``lever``
    names nothing a profile can encode (``lever=None`` recommendations --
    out of scope for a profile by design; workflow advice, not a
    setting). Handles the bare literals in :data:`RECOMMEND_LEVER_MAP`,
    ``ttl.TtlTypeStats.lever``'s per-agent-type sentence form via
    :data:`_AGENT_LEVER_RE` (exactly the same pattern
    ``recommend._lever_scope``/``recommend.render_patch_set`` already use
    to recognise it), and an ``"env:NAME"``-prefixed lever (COV-09) by
    stripping the prefix and checking :data:`ENV_ALLOWLIST` directly --
    ``None`` if ``NAME`` isn't allowlisted, so an unlisted env lever fails
    the same way an unlisted settings/agent key would."""
    if lever in RECOMMEND_LEVER_MAP:
        return RECOMMEND_LEVER_MAP[lever]
    if _AGENT_LEVER_RE.search(lever):
        return ("agent frontmatter", "experimental.cacheTtl")
    if lever.startswith(_ENV_LEVER_PREFIX):
        name = lever[len(_ENV_LEVER_PREFIX):]
        if name in ENV_ALLOWLIST:
            return ("env", name)
        return None
    return None


# -- sanity: keep the dataclass field list and TOP_LEVEL_KEYS in sync -------
#
# A future contributor adding a new Profile field without also adding it
# to _TOP_LEVEL_KEYS (or vice versa) would silently make validate() and
# load_dict() disagree about what a profile may contain. Assert it once
# at import time rather than relying on a test to catch it.
_PROFILE_FIELD_NAMES = {f.name for f in fields(Profile)} - {"source_path"}
_EXPECTED_TOP_LEVEL = {("for_" if k == "for" else k) for k in _TOP_LEVEL_KEYS}
assert _PROFILE_FIELD_NAMES == _EXPECTED_TOP_LEVEL, (
    _PROFILE_FIELD_NAMES,
    _EXPECTED_TOP_LEVEL,
)
